
# PATH for Python packages
export PATH=$PATH:/home/ros/.local/bin

# Display Passthrough Variables
export DISPLAY=$DISPLAY
# export XAUTHORITY=$XAUTHORITY
# export QT_X11_NO_MITSHM=1

# ROS 2 Variables
export ROS_DOMAIN_ID=0
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
unset ROS_LOCALHOST_ONLY
source /home/ros/ros2_ws/install/setup.bash
